import { describe, test, expect } from "bun:test";
import { cleanText, chunkTranscript } from "../src/chunker";

// ---------------------------------------------------------------------------
// cleanText 単体テスト
// ---------------------------------------------------------------------------

describe("cleanText", () => {
  test("[Request interrupted by user] を除去する", () => {
    const input = "[Request interrupted by user]\n実際の質問テキスト";
    expect(cleanText(input)).toBe("実際の質問テキスト");
  });

  test("task-notification XML を除去する", () => {
    const input =
      "<task-notification>\n<task-id>a001c6556e97465df</task-id>\n<tool-use-id>toolu_016G4nxicu6r9nyAQoBA8L6s</tool-use-id>\n<status>completed</status>\n</task-notification>\n残りのテキスト";
    expect(cleanText(input)).toBe("残りのテキスト");
  });

  test("system-reminder XML を除去する", () => {
    const input =
      "<system-reminder>\nThe task tools haven't been used recently.\n</system-reminder>\n続けて";
    expect(cleanText(input)).toBe("続けて");
  });

  test("local-command-caveat XML を除去する", () => {
    const input =
      "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to them.</local-command-caveat>\nls の結果を見て";
    expect(cleanText(input)).toBe("ls の結果を見て");
  });

  test("interrupted と実質テキストが混在する場合", () => {
    const input = "commit\n[Request interrupted by user]\ncommit";
    expect(cleanText(input)).toBe("commit\ncommit");
  });

  test("通常テキストは変更されない", () => {
    const input = "ReactのuseStateとは？";
    expect(cleanText(input)).toBe("ReactのuseStateとは？");
  });

  test("クリーニング後に空になる", () => {
    const input = "[Request interrupted by user]";
    expect(cleanText(input)).toBe("");
  });

  test("複数のXMLタグが混在する場合", () => {
    const input =
      "<system-reminder>\nreminder content\n</system-reminder>\n質問です\n<task-notification>\ntask content\n</task-notification>";
    expect(cleanText(input)).toBe("質問です");
  });
});

// ---------------------------------------------------------------------------
// chunkTranscript 統合テスト（クリーニング統合）
// ---------------------------------------------------------------------------

describe("chunkTranscript with cleaning", () => {
  test("ノイズ入りJSONL → クリーンなQ&A", () => {
    const jsonl = [
      '{"type":"user","message":{"content":"[Request interrupted by user]\\nSQLiteの使い方を教えて"}}',
      '{"type":"assistant","message":{"content":[{"type":"text","text":"SQLiteは軽量なRDBMSです。BunではDatabaseクラスを使って簡単に操作できます。WALモードを有効にするとパフォーマンスが向上します。"}]}}',
    ].join("\n");

    const chunks = chunkTranscript(jsonl);
    // Q から [Request interrupted by user] が除去されていること
    expect(chunks[0].question).toBe("SQLiteの使い方を教えて");
  });

  test("クリーニングで空になったメッセージはスキップされる", () => {
    const jsonl = [
      '{"type":"user","message":{"content":"[Request interrupted by user]"}}',
      '{"type":"assistant","message":{"content":[{"type":"text","text":"何かお手伝いできることはありますか？"}]}}',
      '{"type":"user","message":{"content":"Bunの特徴は？"}}',
      '{"type":"assistant","message":{"content":[{"type":"text","text":"BunはJavaScriptCoreベースの高速ランタイムです。SQLiteが組み込まれており、TypeScriptもネイティブサポートしています。"}]}}',
    ].join("\n");

    const chunks = chunkTranscript(jsonl);
    // 1つ目のQ は空になるのでスキップ、2つ目のQ&Aのみ残る
    expect(chunks).toHaveLength(1);
    expect(chunks[0].question).toBe("Bunの特徴は？");
  });
});
